version: '3'

services:
  mongo:
    image: mongo:4.4.2-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: senha
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

networks:
  mongo-compose-network:
    driver: bridge
